import { createGlobalTheme } from "@vanilla-extract/css";

export const vars = createGlobalTheme(":root", {
  borderRadiusNone: "0",
  borderRadiusSmall: "2px",
  borderRadiusMedium: "4px",
  borderRadiusLarge: "6px",
  borderRadiusXLarge: "8px",
  borderRadiusCircular: "10000px",

  fontSizeBase100: "10px",
  fontSizeBase200: "12px",
  fontSizeBase300: "14px",
  fontSizeBase400: "16px",
  fontSizeBase500: "20px",
  fontSizeBase600: "24px",

  fontSizeHero700: "28px",
  fontSizeHero800: "32px",
  fontSizeHero900: "40px",
  fontSizeHero1000: "68px",

  lineHeightBase100: "14px",
  lineHeightBase200: "16px",
  lineHeightBase300: "20px",
  lineHeightBase400: "22px",
  lineHeightBase500: "28px",
  lineHeightBase600: "32px",
  lineHeightHero700: "36px",
  lineHeightHero800: "40px",
  lineHeightHero900: "52px",
  lineHeightHero1000: "92px",

  fontFamilyBase:
    '"Segoe UI", "Segoe UI Web (West European)", -apple-system, BlinkMacSystemFont, Roboto, "Helvetica Neue", sans-serif',
  fontFamilyMonospace: '"Consolas, "Courier New", Courier, monospace"',
  fontFamilyNumeric:
    'Bahnschrift, "Segoe UI", "Segoe UI Web (West European)", -apple-system, BlinkMacSystemFont, Roboto, "Helvetica Neue", sans-serif',

  fontWeightRegular: "400",
  fontWeightMedium: "500",
  fontWeightSemibold: "600",
  fontWeightBold: "700",

  strokeWidthThin: "1px",
  strokeWidthThick: "2px",
  strokeWidthThicker: "3px",
  strokeWidthThickest: "4px",

  spacingHorizontalNone: "0",
  spacingHorizontalXXS: "2px",
  spacingHorizontalXS: "4px",
  spacingHorizontalSNudge: "6px",
  spacingHorizontalS: "8px",
  spacingHorizontalMNudge: "10px",
  spacingHorizontalM: "12px",
  spacingHorizontalL: "16px",
  spacingHorizontalXL: "20px",
  spacingHorizontalXXL: "24px",
  spacingHorizontalXXXL: "32px",

  spacingVerticalNone: "0",
  spacingVerticalXXS: "2px",
  spacingVerticalXS: "4px",
  spacingVerticalSNudge: "6px",
  spacingVerticalS: "8px",
  spacingVerticalMNudge: "10px",
  spacingVerticalM: "12px",
  spacingVerticalL: "16px",
  spacingVerticalXL: "20px",
  spacingVerticalXXL: "24px",
  spacingVerticalXXXL: "32px",

  durationUltraFast: "50ms",
  durationFaster: "100ms",
  durationFast: "150ms",
  durationNormal: "200ms",
  durationGentle: "250ms",
  durationSlow: "300ms",
  durationSlower: "400ms",
  durationUltraSlow: "500ms",

  curveAccelerateMax: "cubic-bezier(0.9, 0.1, 1, 0.2)",
  curveAccelerateMid: "cubic-bezier(1, 0, 1, 1)",
  curveAccelerateMin: "cubic-bezier(0.8, 0, 0.78, 1)",
  curveDecelerateMax: "cubic-bezier(0.1, 0.9, 0.2, 1)",
  curveDecelerateMid: "cubic-bezier(0, 0, 0, 1)",
  curveDecelerateMin: "cubic-bezier(0.33, 0, 0.1, 1)",
  curveEasyEaseMax: "cubic-bezier(0.8, 0, 0.2, 1)",
  curveEasyEase: "cubic-bezier(0.33, 0, 0.67, 1)",
  curveLinear: "cubic-bezier(0, 0, 1, 1)",

  breakpointsMobile: "320px",
  breakpointsTablet: "768px",
  breakpointsDesktop: "1024px",
  breakpointsWide: "1440px",

  zIndexDropdown: "100",
  zIndexSticky: "200",
  zIndexModal: "300",
  zIndexPopover: "400",
  zIndexTooltip: "500",
  zIndexToast: "600",
});
